# Generated by Django 5.1.2 on 2024-10-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0002_remove_movie_genres_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(default=0, upload_to='movie_images'),
        ),
    ]
